### ISSUE TITLE
IndexOptionsConflict for chunk collection

### ISSUE THREAD

**Issue by sekko27** [denodrivers/mongo#364]
If the chunks collection has index with the same options we get IndexOptionsConflict error ( https://www.mongodb.com/docs/manual/reference/command/createIndexes/#considerations )

deno_mongo checks index using options **filename** and **uploadDate** for chunks collection too, see https://github.com/denodrivers/deno_mongo/blob/f5b1c0a3ce7e7d542c90899ead1425cdc94ada31/src/gridfs/indexes.ts#L85-L97

It should based on **files_id** and **n** as the module uses at https://github.com/denodrivers/deno_mongo/blob/f5b1c0a3ce7e7d542c90899ead1425cdc94ada31/src/gridfs/indexes.ts#L18-L32

Checked for 0.30.1

**Comment by erfanium** [comment]
@sekko27 Can you create a PR for it? thanks

**Comment by lucsoft** [comment]
Looks like this is fixed
