### ISSUE TITLE
Question: Naming of the repo

### ISSUE THREAD

**Issue by PodaruDragos** [denodrivers/mongo#367]
Hello, this is just a question about the naming in this whole repo.
Why is this repo not named just mongo ? since all the others don't contain deno_ in front

**Comment by erfanium** [comment]
@PodaruDragos just for you

**Comment by PodaruDragos** [comment]
@erfanium oh thanks 😄

**Comment by lucsoft** [comment]
@erfanium doesn't this break deno.land/x ?

**Comment by erfanium** [comment]
@lucsoft nope, I had change deno repo names before
