### ISSUE TITLE
GridFS: localize test image files + remove a unnecessary test

### ISSUE THREAD

**Issue by erfanium** [denodrivers/mongo#369]
https://deno.land/images/deno_logo.png
https://deno.land/images/deno_logo_4.gif

Also I don't think `GridFS: Echo large Image (compare with different Image)` test is necessary, @lucsoft what is the purpose of this test?

**Comment by lucsoft** [comment]
to verify that the other test works. its a bad path test. i don't see any reason to remove it

having bad path tests is a good thing
