### ISSUE TITLE
MongoError: findAndModify - Either an update or remove=true must be specified

### ISSUE THREAD

**Issue by aldaMarMu** [denodrivers/mongo#373]
Hello,

I am trying to use `findAndModify` to update one document in my `centers` collection but it gives me the following error: 

`MongoError: {"ok":0,"errmsg":"Either an update or remove=true must be specified","code":9,"codeName":"FailedToParse"}`

This is the code I used:

```typescript
    const newCenter = await db.collection("centers").findAndModify({
      query:{ _id: new ObjectId("62e7e66fdfa1d9392721647b") },
      update: { $set: {name: "test"}},
      new: true
    });
```

If I execute the same query on mongo shell or with a mongo client, it works perfectly.

Thank you!

**Comment by erfanium** [comment]
@aldaMarMu findAndModify is deprecated. use either one of `findOneAndUpdate`, `findOneAndReplace` or `findOneAndDelete`

**Comment by erfanium** [comment]
Oh damn, we have forgot to implement these methods.
for now check this
```js
const newCenter = await db.collection("centers").findAndModify({
  _id: new ObjectId("62e7e66fdfa1d9392721647b"),
  }.{
  update: { $set: {name: "test"}},
  new: true
});
```

**Comment by aldaMarMu** [comment]
Hi @erfanium, thank you very much. It works! 

I will use `findAndModify` until `findOneAndUpdate` is available.
