### ISSUE TITLE
MongoDB not working search for an object by its ObjectId

### ISSUE THREAD

**Issue by WorrenGilgamesh** [denodrivers/mongo#384]
Here is the Deno discord threat of the problem:
https://discord.com/channels/684898665143206084/1054548873844105326

Here is the Stackoverflow description of the problem:
https://stackoverflow.com/q/74857334/8272938

**Comment by erfanium** [comment]
I don;t see any problem here.
ObjectId is not an string. string is not an ObjectId
They are two different data types in bson and MongoDB. if some tools like mongoose let you to use an string instead of objectId, it's not the official driver feature
